version: '2.2'

include:
    - docker/docker-mysql.yml

services:
    test:
        build:
            context: .
            target: ospos_test
        depends_on:
            - mysql
        container_name: ospos_test
        environment:
            - CI_ENVIRONMENT=testing
            - ENCRYPTION_KEY=
            - MYSQL_HOST_NAME=mysql
            - MYSQL_DATABASE=ospos
            - MYSQL_USERNAME=admin
            - MYSQL_PASSWORD=pointofsale
        command:
            - /bin/sh
            - -c
            - >-
                /bin/wait-for-it.sh mysql:3306 -- &&
                CI_ENVIRONMENT=production php docker/migrations.php migrate &&
                CI_ENVIRONMENT=production php spark cache:clear &&
                /app/vendor/bin/phpunit --configuration /app/phpunit.xml.dist --no-coverage
        ports:
            - "80:80"
