<?php

namespace Tests;

use App\Controllers\Sales as SalesController;
use App\Libraries\Sale_lib;
use CodeIgniter\HTTP\IncomingRequest;
use CodeIgniter\HTTP\URI;
use CodeIgniter\HTTP\UserAgent;
use CodeIgniter\Test\CIUnitTestCase;
use Config\App;
use ReflectionClass;
use RuntimeException;

/**
 * Covers the register's reduced cart-row request when editing a sale item.
 *
 * @internal
 */
final class TillEditItemTest extends CIUnitTestCase
{
    /**
     * Loads the locale helper used by the controller's decimal validation.
     */
    protected function setUp(): void
    {
        parent::setUp();

        helper('locale');
    }

    /**
     * Removes the cart shared by the controller and its sale library.
     */
    protected function tearDown(): void
    {
        session()->remove('sales_cart');

        parent::tearDown();
    }

    /**
     * Stores a changed quantity when the removed discount input is absent.
     */
    public function testEditingCartLineWithoutDiscountStoresNewQuantity(): void
    {
        [$controller, $saleLibrary, $reloadException] = $this->makeController([
            'location'    => '1',
            'item_id'     => '7',
            'price'       => '12.00',
            'quantity'    => '2.00',
            'description' => '',
            'serialnumber' => '',
        ]);

        $this->invokeEditItem($controller, $reloadException);

        $cart = $saleLibrary->get_cart();

        $this->assertSame('2', $cart[1]['quantity']);
        $this->assertSame('12', $cart[1]['price']);
        $this->assertSame('0', $cart[1]['discount']);
    }

    /**
     * Keeps an explicitly posted discount when the legacy input is present.
     */
    public function testEditingCartLineWithExplicitDiscountAppliesDiscount(): void
    {
        [$controller, $saleLibrary, $reloadException] = $this->makeController([
            'location'     => '1',
            'item_id'      => '7',
            'price'        => '12.00',
            'quantity'     => '2.00',
            'discount'     => '1.50',
            'discount_type' => (string) FIXED,
            'description'  => '',
            'serialnumber' => '',
        ]);

        $this->invokeEditItem($controller, $reloadException);

        $cart = $saleLibrary->get_cart();

        $this->assertSame('1.5', $cart[1]['discount']);
        $this->assertSame((string) FIXED, $cart[1]['discount_type']);
        $this->assertSame(21.0, (float) $cart[1]['discounted_total']);
    }

    /**
     * Uses a safe integer default when a hand-built request omits the location.
     */
    public function testEditingCartLineWithoutLocationDoesNotThrow(): void
    {
        [$controller, $saleLibrary, $reloadException] = $this->makeController([
            'item_id'     => '7',
            'price'       => '12.00',
            'quantity'    => '2.00',
            'description' => '',
            'serialnumber' => '',
        ]);

        $this->invokeEditItem($controller, $reloadException);

        $this->assertSame('2', $saleLibrary->get_cart()[1]['quantity']);
    }

    /**
     * Posts the exact reduced field set generated by the register row form.
     */
    public function testRegisterRowFieldSetPostsWithoutRemovedInputs(): void
    {
        $post = [
            'location'    => '1',
            'item_id'     => '7',
            'price'       => '12.00',
            'quantity'    => '2.00',
            'description' => '',
            'serialnumber' => '',
        ];

        [$controller, $saleLibrary, $reloadException] = $this->makeController($post);

        $this->invokeEditItem($controller, $reloadException);

        $this->assertSame('2', $saleLibrary->get_cart()[1]['quantity']);
        $this->assertArrayNotHasKey('discount', $post);
        $this->assertArrayNotHasKey('discount_type', $post);
    }

    /**
     * Builds a controller with a real cart edit and stops before the register reload.
     *
     * @return array{0: SalesController, 1: Sale_lib, 2: RuntimeException}
     */
    private function makeController(array $post): array
    {
        $reloadException = new RuntimeException('register reload reached');
        $saleLibrary     = $this->getMockBuilder(Sale_lib::class)
            ->onlyMethods(['out_of_stock', 'reset_cash_rounding'])
            ->getMock();

        $expectedLocation = (int) ($post['location'] ?? 0);
        $saleLibrary->expects($this->once())
            ->method('out_of_stock')
            ->with(7, $expectedLocation)
            ->willReturn('');
        $saleLibrary->method('reset_cash_rounding')->willThrowException($reloadException);
        $saleLibrary->set_cart([
            1 => [
                'item_id'         => 7,
                'item_location'   => 1,
                'description'     => '',
                'serialnumber'    => '',
                'quantity'        => '1',
                'price'           => '10',
                'discount'        => '0',
                'discount_type'   => PERCENT,
                'total'           => '10',
                'discounted_total' => '10',
            ],
        ]);

        $request = new IncomingRequest(new App(), new URI('/sales/editItem/1'), null, new UserAgent());
        $request->setGlobal('post', $post);
        $request->setGlobal('request', $post);
        $this->assertSame($post, $request->getPost());

        $controller = (new ReflectionClass(SalesController::class))->newInstanceWithoutConstructor();
        $reflection = new ReflectionClass($controller);

        $requestProperty = $reflection->getProperty('request');
        $requestProperty->setAccessible(true);
        $requestProperty->setValue($controller, $request);

        $sessionProperty = $reflection->getProperty('session');
        $sessionProperty->setAccessible(true);
        $sessionProperty->setValue($controller, session());

        $saleLibraryProperty = $reflection->getProperty('sale_lib');
        $saleLibraryProperty->setAccessible(true);
        $saleLibraryProperty->setValue($controller, $saleLibrary);

        return [$controller, $saleLibrary, $reloadException];
    }

    /**
     * Runs the edit action and confirms execution reached its normal reload point.
     */
    private function invokeEditItem(SalesController $controller, RuntimeException $reloadException): void
    {
        try {
            $controller->postEditItem('1');
        } catch (RuntimeException $exception) {
            $this->assertSame($reloadException, $exception);

            return;
        }

        $this->fail('The controller did not reach the register reload.');
    }
}
